### ISSUE TITLE
HPA Issue with CSE 0.7.1 Chart

### ISSUE THREAD

**Issue by pescetto** [virtru-corp/virtru-charts#44]
When using the `v0.7.1` helm chart for cse, we're getting the following error:
```bash
error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource):
unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource,
ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource,
ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource,
ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource]
```

It looks like [this change](https://github.com/virtru-corp/virtru-charts/commit/5abab473d3008441e7c4501fab8066ee164a8641#diff-638dee3a020be730b555292e7e4137940cac7bc9d7151126d177fddf11e7fffaR2) updated the API for HPA, but according to the [Kubernetes HPA docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics), it looks like the structure was changed from this:
```yaml
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
```

to this:
```yaml
metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
```

Here's [another doc](https://cloud.google.com/kubernetes-engine/docs/how-to/horizontal-pod-autoscaling#multiple-metrics) from Google GKE showing an example configuration supporting the new conventions.
